name: (CI) Build gatling docker image

# On manual trigger
on: workflow_dispatch

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  go:
    runs-on: ubuntu-latest

    steps:
      - name: == ABOUT ==
        run: |
          echo "Ticket: ${{ github.event.inputs.ticket }}" 
          echo "Simulation: ${{ github.event.inputs.simulation }}"
          echo "   Number of users: ${{ github.event.inputs.userCount }}"
          echo "   Time for ramping users: ${{ github.event.inputs.rampDuration }}"
          echo "   Test duration: ${{ github.event.inputs.testDuration }}"

      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn gatling:test
      
      # Exporting .jar as a artifact
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
