name: (CI) Build gatling docker image

# On manual trigger
on: workflow_dispatch

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  go:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn gatling:test
      
      # Exporting .jar as a artifact
      - run: mkdir staging && cp /home/runner/work/Gatling-on-GithubActions/Gatling-on-GithubActions/target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
