name: (CT) Launch a simulation

on: 
  workflow_dispatch:
    inputs:
      ticket:
        description: 'Ticket #'
        required: false
      simulation:
        description: 'Simulation'     
        required: true
        default: 'BasicTest'
      userCount:
        description: 'Number of users'     
        required: true
        default: '1'
      rampDuration:
        description: 'Time for ramping #users (sec)'     
        required: true
        default: '10'
      testDuration:
        description: 'Test duration (sec)'     
        required: true
        default: '60'

jobs:
  go:
    runs-on: ubuntu-latest

    steps:
      - name: == ABOUT ==
        run: |
          echo "Ticket: ${{ github.event.inputs.ticket }}" 
          echo "Simulation: ${{ github.event.inputs.simulation }}"
          echo "   Number of users: ${{ github.event.inputs.userCount }}"
          echo "   Time for ramping users: ${{ github.event.inputs.rampDuration }}"
          echo "   Test duration: ${{ github.event.inputs.testDuration }}"

      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn gatling:test -DuserCount=${{ github.event.inputs.userCount }} -DrampDuration=${{ github.event.inputs.rampDuration }} DtestDuration=${{ github.event.inputs.testDuration }} -Dgatling.simulationClass=simulation.${{ github.event.inputs.simulation }}
      - name: Save results
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: /home/runner/work/Gatling-on-GithubActions/Gatling-on-GithubActions/target/gatling/*
