name: Launch a simulation

on: 
  workflow_dispatch:
    inputs:
      ticket:
        description: 'Ticket #'
        required: true
      simulation:
        description: 'Simulation'     
        required: true
        default: 'BasicTest'

jobs:
  go:
    runs-on: ubuntu-latest

    steps:
      - name: == ABOUT ==
        run: |
          echo "Ticket: ${{ github.event.inputs.ticket }}" 
          echo "Simulation: ${{ github.event.inputs.simulation }}"

      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn gatling:test -Dgatling.simulationClass=simulation.${{ github.event.inputs.simulation }}
      - name: Save results
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: /home/runner/work/Gatling-on-GithubActions/Gatling-on-GithubActions/target/gatling/*
